time_collected: 400
sensors_used:
  Microphone: True
  BMP280: True
  PIR: True
  VEML7700: True
  SHT31D: True
  Voltkey: False
  TestSensor: False
sensor_sample_rates:
  Microphone: 48000
  BMP280: 50
  PIR: 2
  VEML7700: 40
  SHT31D: 40
  Voltkey: 2000
  TestSensor: 44100
chunk_sizes:
  Microphone: 2000
  BMP280: 5
  PIR: 1
  VEML7700: 4
  SHT31D: 4
  Voltkey: 500
  TestSensor: 1024
